### ISSUE TITLE
Deeplinking crashes if in page in tab

### ISSUE THREAD

**Issue by arjendevos** [web-ridge/react-native-ridge-navigation#60]
`home/cart` -> is a tab page. Works perfectly fine if we deeplink like: `app://home/cart`
`home/cart/checkout` -> is page inside the `home/cart` tab. Doesn't work.

![WhatsApp Image 2023-03-01 at 13 30 38](https://user-images.githubusercontent.com/67794681/222163729-500981a6-a185-413a-a028-ebf70f420c5a.jpeg)

**Comment by RichardLindhout** [comment]
should work now

/rootPath/bottomTabPath/screenPath/:param
